on:
  issue_comment:
    types:
      - created

jobs:
  runs-on: ubuntu-latest
  test1:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.issue.body, 'build please') }}
  steps:
    - name: Log branch name
      run: |
        echo github.ref: ${{ github.ref }} github.head_ref: ${{ github.head_ref }}
