on:
  issue_comment:
    types:
      - created

jobs:
  test1:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.issue_comment.comment, 'build please') }}
    runs-on: ubuntu-latest
    steps:
      - name: Log branch name
        run: |
          echo github.ref: ${{ github.ref }} github.head_ref: ${{ github.head_ref }}
